#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/blue?serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: admin12345
#mybatis:
#  type-aliases-package: com.wwc.question_answer.mybatis.entity
#server:
#  port: 8080